# POST http://localhost:5000/user/register
# Content-Type: application/json

# {
#     "username":"Shankar",
#     "password":"98989",
#     "role":"student",
#     "fullName":"chinta shankar",
#     "contactNumber":"9876543345",
#     "email":"shankar@gmail.com",
#     "address":"Godavari",
#     "dateOfBirth":"2003-08-13",
#     "subject":"math",
#     "yearsOfExperience":34

# }
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username":"Shankar",
       "password":"98989"
}